### ISSUE TITLE
UPSERT statement failing with "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by amalts** [Boostport/avatica#34]
rows, err := db.Query(`upsert into us_population values('BA','San jose',3844829)`) 
This code was failing due to nil pointer dereference. Stack trace given below.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1245246]

goroutine 1 [running]:
github.com/Boostport/avatica.newRows(0xc4200f81a0, 0x13, 0xc420100070, 0x1, 0x1, 0x1417d20)
        /workspace/go/src/github.com/Boostport/avatica/rows.go:145 +0x186
github.com/Boostport/avatica.(*conn).query(0xc4200f81a0, 0x1664070, 0xc420010270, 0x12f72a8, 0x39, 0x145ff50, 0x0, 0x0, 0x12418f0, 0x5, ...)
        /workspace/go/src/github.com/Boostport/avatica/connection.go:181 +0x242
github.com/Boostport/avatica.(*conn).QueryContext(0xc4200f81a0, 0x1418ae0, 0xc420010270, 0x12f72a8, 0x39, 0x145ff50, 0x0, 0x0, 0x2a01060, 0x104f520, ...)
        /workspace/go/src/github.com/Boostport/avatica/connection_go18.go:78 +0x1bd
database/sql.ctxDriverQuery(0x1418ae0, 0xc420010270, 0x2a01060, 0xc4200f81a0, 0x12f72a8, 0x39, 0x145ff50, 0x0, 0x0, 0x1028bce, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/ctxutil.go:48 +0x28d
database/sql.(*DB).queryConn.func1()
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:1264 +0x99
database/sql.withLock(0x1415ea0, 0xc4201061c0, 0xc420057cf0)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:2545 +0x65
database/sql.(*DB).queryConn(0xc4200de640, 0x1418ae0, 0xc420010270, 0xc4201061c0, 0xc4200fa160, 0x12f72a8, 0x39, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:1265 +0x671
database/sql.(*DB).query(0xc4200de640, 0x1418ae0, 0xc420010270, 0x12f72a8, 0x39, 0x0, 0x0, 0x0, 0x10b3801, 0xc420057ed0, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:1250 +0x12f
database/sql.(*DB).QueryContext(0xc4200de640, 0x1418ae0, 0xc420010270, 0x12f72a8, 0x39, 0x0, 0x0, 0x0, 0x8, 0x12e8348, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:1227 +0xb8
database/sql.(*DB).Query(0xc4200de640, 0x12f72a8, 0x39, 0x0, 0x0, 0x0, 0x0, 0x145ff50, 0x0)
        /usr/local/Cellar/go/1.8.1/libexec/src/database/sql/sql.go:1241 +0x82
main.testLoad()```

**Comment by F21** [comment]
Hey @amalts ,

Thanks for bringing this to my attention. Since you are modifying data, you will need to use `db.Exec()` to perform the upsert.

Having said that, having code panicking like this is also a bad idea too. 

Can you please provide the following information?
- What database and version you are using/ (e.g. Phoenix 4.11).
- What version of Avatica/Phoenix Query Server you're using.

According to the protobuf definitions for `ResultSetResponse`, the `signature` field should always be present. See https://calcite.apache.org/avatica/docs/protobuf_reference.html#resultsetresponse

I'll clarify the issue regarding the `signature` field with the maintainers of Avatica to see how we should proceed.

Thanks again!
